spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-shop
    username: postgres
    password: ali.1381
    driverClassName: org.postgresql.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop